version: '3.8'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "8090:80"
      - "8150:443"
    volumes:
      - ./dev-nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certs/localhost.pem:/etc/nginx/ssl/localhost.pem
      - ./certs/localhost-key.pem:/etc/nginx/ssl/localhost-key.pem
    depends_on:
      - frontend
      - backend

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - REACT_APP_BACKEND_URL=https://localhost:8150
        - REACT_APP_BACKEND_WS_URL=wss://localhost:8150/ws
        - NODE_ENV=local
    expose:
      - "3000"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    expose:
      - "5001"
    environment:
      - PORT=5001
      - NODE_ENV=local 