version: '3.8'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "8090:80"
      - "8150:443"
    volumes:
      - ./dev-nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certs/localhost.pem:/etc/nginx/ssl/localhost.pem
      - ./certs/localhost-key.pem:/etc/nginx/ssl/localhost-key.pem
    depends_on:
      - frontend
      - backend
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "443"]
      interval: 5s
      timeout: 3s
      retries: 3

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - REACT_APP_BACKEND_URL=https://localhost:8150
        - REACT_APP_BACKEND_WS_URL=wss://localhost:8150/ws
        - NODE_ENV=local
    expose:
      - "3000"
    depends_on:
      - backend
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "3000"]
      interval: 5s
      timeout: 3s
      retries: 3

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    expose:
      - "5001"
    environment:
      - PORT=5001
      - NODE_ENV=local
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "5001"]
      interval: 5s
      timeout: 3s
      retries: 3

  startup_message:
    image: alpine
    depends_on:
      nginx:
        condition: service_healthy
      frontend:
        condition: service_healthy
      backend:
        condition: service_healthy
    command: |
      sh -c '
        echo "\n\n🚀 All services are up and running!"
        echo "Frontend is available at https://localhost:8150"
        echo "Backend API is available at https://localhost:8150/api"
        echo "WebSocket is available at wss://localhost:8150/ws"
      ' 